xiaoyeli/superlu

.gitignore, CMakeLists.txt
Sherry,
I found a few issues with the current 'master' branch  Two of the issues mentioned below are fixed by commits in the PR:
1) The generated file `make.inc` is no longer being ignored.  (This is fixed in the new PR.)
2) The built-in CBLAS is not on by default and ignores TPL_BLAS_LIBRARIES.  That is incompatible with the XSDK configure standard and kills library interoperability.  When USE_XSDK_DEFAULTS=ON, it must *not* use the use the built-in CBLAS by default.  (This is fixed in the new PR.)
3) There is no auotmated testing for the user example at all, even for the narrow use cases where it currently works.  That is asking for the examples to be broken when users try to use it. (I did not fix this but this is not an issues for xSDK.)
Can you please just accept my new pull request? …
=> Fix a few remaining issues with CMake build and git (SDK-26)

SRC/CMakeLists.txt
Using [GnuInstallDirs](https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html) has several advantages:
* The correct directories are used, including on Debian (where libs go into, e.g, /usr/lib/<multiarch-tuple>). This is the only change from the previous behavior, and it will only occur on Debian systems.
* One can easily override the default directories by specifying, e.g., `-DCMAKE_INSTALL_INCLUDEDIR=/my/custom/path` at configuration.
=> use GNUInstallDirs

SRC/cutil.c, SRC/dutil.c, SRC/sutil.c, SRC/zutil.c, TESTING/cdrive.c, TESTING/ddrive.c, TESTING/sdrive.c, TESTING/zdrive.c
Newer compilers emits according warnings.
=> Explicitly declare function return type as int

EXAMPLE/cfgmr.c, EXAMPLE/dfgmr.c, EXAMPLE/sfgmr.c, EXAMPLE/zfgmr.c
rpmlint complains upon building RPM packages.
Their new address is according to http://www.fsf.org/about/contact/
Free Software Foundation
51 Franklin Street, Fifth Floor
Boston, MA 02110-1301
USA
GPLv2 moved to http://www.gnu.org/licenses/gpl-2.0.txt
=> Update FSF address in example files

SRC/clacon2.c, SRC/dmach.c, SRC/ilu_cdrop_row.c, SRC/ilu_zdrop_row.c, SRC/slacon2.c, SRC/smach.c, SRC/sp_ienv.c, SRC/zlacon2.c
Declarations of external routines, found by adding gcc flag "-Wimplicit-function-declaration". 
From our gentoo linux QA.
=> add declarations to avoid implicit declarations

TESTING/CMakeLists.txt, TESTING/MATGEN/CMakeLists.txt
Link errors revealed by
```
-DCMAKE_SHARED_LINKER_FLAGS="$CMAKE_SHARED_LINKER_FLAGS -Wl,--no-undefined"
```
=> fix library dependencies

INSTALL/superlu_timer.c, SRC/colamd.c, SRC/superlu_timer.c
The link changes were identified in SciPy
The `CLK_TCK` is an effort to cleanup warning generated during SciPy Build.
Happy to break these into two pulls if you prefer.
=> Small fixes from SciPy work

SRC/slu_util.h
The macro is called SUPERLU_MAJOR_VERSION, not SUPERLU_MAIN_VERSION
=> slu_util: Minor documentation correction

SRC/CMakeLists.txt
This makes adding the m library conditional to not being on Windows.  Windows now builds.
=> Remove m library on Windows

.github/workflows/test.yml, SRC/dGetDiagU.c
It would be really useful to have CI for this library.  
This adds CI using GitHub Actions as discussed in https://github.com/xiaoyeli/superlu/pull/18#issuecomment-751284386
The library is built with gcc and clang then tests are run. Note that there are currently segfaults in tests, not sure if it's normal.  
I also had to apply a small fix for including `slu_ddefs.h` as otherwise I was getting,
```
gcc -O3 -g -DAdd_ -DUSE_VENDOR_BLAS -c dGetDiagU.c 
dGetDiagU.c:32:10: fatal error: slu_ddefs.h: No such file or directory
32 | #include <slu_ddefs.h>
|          ^~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:115: dGetDiagU.o] Error 1
```
closes https://github.com/xiaoyeli/superlu/pull/18
**Note:** CI is triggered on my fork https://github.com/rth/superlu/tree/add-ci so I'm not …
=> Add CI with GitHub Actions

SRC/dgstrs.c, SRC/dmemory.c, SRC/slu_ddefs.h
BUG: For big linear systems **AX = B** such as when the right hand side B is of size 46679 x 46680 containing doubles, `dgssv` gets stuck in a runtime memory error that looks like below:
```
SUPERLU_MALLOC failed for buf in doubleCalloc()
at line 693 in file superlu/SRC/dmemory.c
```
**dgssv** in turn calls **dgstrs**, with this last one calling `doubleCalloc(n * nrhs)` where `int n = L->nrow` and `int nrhs = B->ncol`. Finally, **doubleCalloc** makes a call to the **SUPERLU_MALLOC** macro
```
buf = (double*) SUPERLU_MALLOC((size_t)n * sizeof(double));
if( !buf ) {
ABORT("SUPERLU_MALLOC failed for buf in doubleCalloc()\n");
}
```
with the macro being defined as the `void* superlu_python_module_malloc(size_t size)` function that sets some member `mem_ptr = malloc(size);` and returns …
=> BUG: fix memory error caused from overflowing signed 32-bit int input to doubleCalloc

EXAMPLE/cfgmr.c, EXAMPLE/clinsolx.c, EXAMPLE/dfgmr.c, EXAMPLE/sfgmr.c, EXAMPLE/sp_ienv.c, EXAMPLE/superlu.c, EXAMPLE/zfgmr.c, TESTING/cdrive.c, TESTING/ddrive.c, TESTING/sdrive.c, TESTING/zdrive.c
Improving the merge request from @fweimer-rh.
Supersedes #76
=> C99 compatibility fixes

SRC/creadMM.c, SRC/creadtriple.c, SRC/dreadMM.c, SRC/dreadtriple.c, SRC/sreadMM.c, SRC/sreadtriple.c, SRC/zreadMM.c, SRC/zreadtriple.c
@xiaoyeli Some more fixes, please merge.
=> Reduce warnings and fix bugs in ?readrhs

SRC/cgscon.c, SRC/cgsitrf.c, SRC/cgssv.c, SRC/clacon2.c, SRC/dgscon.c, SRC/dgssv.c, SRC/dmach.c, SRC/heap_relax_snode.c, SRC/ilu_heap_relax_snode.c, SRC/input_error.c, SRC/mc64ad.c, SRC/scsum1.c, SRC/sgscon.c, SRC/sgssv.c, SRC/smach.c, SRC/util.c, SRC/zgscon.c, SRC/zgsitrf.c, SRC/zgssv.c, SRC/zlacon2.c, TESTING/MATGEN/clacgv.c, TESTING/MATGEN/clarnd.c, TESTING/MATGEN/dlarnd.c, TESTING/MATGEN/slarnd.c, TESTING/MATGEN/zlacgv.c, TESTING/MATGEN/zlarnd.c
Fix most of the warnings emitted by Clang with `-Wall -Wpedantic -std=c11".
=> Fix many clang warnings

DoxyConfig, Makefile
This added the missing files when building the Doxygen documentation with Make. When using CMake, the DoxyConfig is generated on the fly and it already contains these two files.
@xiaoyeli This should fix you Doxygen problems.
Over the time, we have to unify the way we build documentation or drop support for plain Makefiles and support only CMake.
=> [doxygen] Include modules.txt and mainpage.txt in DoxyConfig

CMakeLists.txt, DOC/CMakeLists.txt
From now on, "make doc" (or ninja doc or whatever) does always build the Doxygen documentation, given Doxygen is found. When passing "enable_doc=1" to cmake, "make doc" is added to the default target, i.e., when running "make" (or "make all" or "ninja") Doxygen documentation is automatically created.
=> [cmake] Alter way of handling enable_doc

SRC/slu_cdefs.h, SRC/slu_zdefs.h
The argument was changed in slu_sdefs.h / slu_ddefs.h and remained in slu_cdefs.h / slu_zdefs.h. This leads to incompatible declarations.
This problem occurs when slu_sdefs.h and slu_cdefs.h are included together, see for example https://github.com/FreeFem/FreeFem-sources/issues/272
=> Adjust forward delcaration of float/double Malloc/Calloc

CMakeLists.txt, DOC/CMakeLists.txt
doxygen_add_docs must not be called when Doxygen was not found.
ALL in doxygen_add_docs requries CMake 3.12 or newer.
ALL in doxygen_add_docs comes after files or dirs
Fixes #101
=> [cmake] Fix Doxygen call

EXAMPLE/clinsolx.c, EXAMPLE/clinsolx1.c, EXAMPLE/clinsolx2.c, EXAMPLE/clinsolx3.c, EXAMPLE/dlinsolx.c, EXAMPLE/dlinsolx1.c, EXAMPLE/dlinsolx2.c, EXAMPLE/dlinsolx3.c, EXAMPLE/slinsolx.c, EXAMPLE/slinsolx1.c, EXAMPLE/slinsolx2.c, EXAMPLE/slinsolx3.c, EXAMPLE/zlinsolx.c, EXAMPLE/zlinsolx1.c, EXAMPLE/zlinsolx2.c, EXAMPLE/zlinsolx3.c, TESTING/cdrive.c, TESTING/ddrive.c, TESTING/sdrive.c, TESTING/zdrive.c
This fixes a MSVC warning about uninitialized pointers of the `work` arrays in examples and tests.
As per request in https://github.com/xiaoyeli/superlu/pull/107#issuecomment-1666471748
=> Fix uninitialized pointer warning in examples and tests

MATLAB/mexsuperlu.c, MATLAB/superlu.m, SRC/dgstrf.c, SRC/dpivotL.c
@xiaoyeli 
As I communicated to you via email on July 24th, the current version of sequential SuperLU has a bug where rank deficient rectangular matrices are not computed properly.  This is an important application as the LU decomposition of a sparse matrix is required for the Null Space Method of solving the Karush–Kuhn–Tucker (KKT) matrix which arises in Quadratic Programming applications such as constrained numerical minimization (see attached reference paper).
https://www.numerical.rl.ac.uk/people/rees/pdf/RAL-TR-2014-016.pdf
After doing some more testing, the bug does not occur for all rank deficient rectangular matrices, nor is it limited to rectangular matrices.  A minimum example of a matrix in which this problem arises is (given in (row, col, value) notation):
(0, 0, 1.0)
(1, 0, …
=> Rank Deficient Matrices

SRC/clangs.c, SRC/dlangs.c, SRC/slangs.c, SRC/zlangs.c
Fixes a usage of uninitialized variable `value` in `[cdsz]langs.c` if the abort conditions are triggered. Yes this isn't a true usage since `ABORT` will call `exit()` but it still causes a compiler warning in some cases.
This pops up whenever SciPy is compiled with LLVM, which happens to be configured to emit this warning:
```
[504/1606] Compiling C object scipy/sparse/linalg/_dsolve/libsuperlu_lib.a.p/SuperLU_SRC_clangs.c.o
../scipy/sparse/linalg/_dsolve/SuperLU/SRC/clangs.c:104:16: warning: variable 'value' is used uninitialized whenever 'if' condition is false [-Wsometimes-uninitialized]
} else if (strncmp(norm, "I", 1)==0) {
^~~~~~~~~~~~~~~~~~~~~~~~
../scipy/sparse/linalg/_dsolve/SuperLU/SRC/clangs.c:126:13: note: uninitialized use occurs here
return (value);
^~~~~ …
```
=> Fix usage of uninitialized variable `value`

README, TESTING/CMakeLists.txt, TESTING/runtest.cmake
This is a split-up version of #112. @wo80, I hope you do not feel offended by me chopping your merge request. I think this increases the quality of the contribution. Further, I hope that I did not introduce errors, it was a very manual task.
@xiaoyeli What do you think, do you pref this over #112?
=> [cmake] Simplify creation of tests

TESTING/CMakeLists.txt
=> [cmake] fix arguments for add_superlu_test

.github/workflows/test.yml, EXAMPLE/CMakeLists.txt, SRC/util.c, TESTING/CMakeLists.txt
Open issues:
1. Compiling the SuperLU library fails without an error message.
2. The optional dependency WinGetOps should be added to the runner to run the tests
Until #131 is merged, this based on top of this branch.
=> Draft: add windows test runner

CMakeLists.txt, FORTRAN/CMakeLists.txt
Do not rely on external sed, use CMake regex instead.
Do not create intermediate files temp.fh and copy of superlu_config.h
Create config file on CMake run and not with target of its own
=> [cmake] Improve generating of superlu_config.fh

.github/workflows/test.yml
This reverts commit 0559d56084de64c7d2384e49165f79b2fd0a601f.
Fixes #134.
=> [ci] Re-enable running tests on Windows as segfaults in tests got fixed"

CMakeLists.txt, EXAMPLE/dlinsol.c
Final touches to resolve everything proposed by Christian in #132.
=> CI: Suppress Visual C security warnings

SRC/cgscon.c, SRC/dgscon.c, SRC/sgscon.c, SRC/zgscon.c
The documentation of [dgscon](https://github.com/xiaoyeli/superlu/blob/86ea4b3cf0c7b31ecc58038428515b92f78571c0/SRC/dgscon.c#L40) gives conflicting information about how its input arguments `L` and `U` have to be computed:
- In the main text, it refers to a function `DGETRF` which, to my knowledge, does not exist in SuperLU. 
- In the description of the arguments, it refers to [`dgstrf`](https://github.com/xiaoyeli/superlu/blob/86ea4b3cf0c7b31ecc58038428515b92f78571c0/SRC/dgstrf.c).
The proposed change replaces `DGETRF` by `DGSTRF` in the comments in the code. It seems that the html documentation are also part of the repo, and would therefore need to be rebuilt.
As a side question, I was wondering if it is possible to use `dgscon` with an incomplete LU decomposition formed by `dgsitrf`? …
=> Fix typo in documentation of gstrs

CMakeLists.txt, SRC/slu_scomplex.h
The macro #define complex broke code that used complex. The typedef is only provided, when enbaled with the CMake option enable_compatibility_complex.
=> Replace #define complex by optional typedef

EXAMPLE/citersol.c, EXAMPLE/ditersol.c, EXAMPLE/sitersol.c, EXAMPLE/zitersol.c
[example] Remove unnecessary include unistd.h from ?itersol.c
=> Fixes broken Windows CI builds.

SRC/colamd.c
v4.5.6 relicensed this file under 3-clause BSD instead of LGPL.
Fixes https://github.com/xiaoyeli/superlu/issues/145
=> Update colamd.c to SuiteSparse v4.5.6.

CMakeLists.txt
This reverts parts of commit 367fd39713dc8efe1edea95b5bafb4863b9b6d0b.
The use of `enable_examples` is in EXAMPLES/CMakeLists.txt. The advantage of the solution is that even with disabled enable_examples the examples can be manually built.
=> [cmake] Revert "make use of "enable_examples" in CMakeLists.txt"

CMakeLists.txt
This allows building the documentation without setting a flag only by running "make doc" / "ninja doc".  
The currently implemented solution by 2c8ef7da153e87745f04f968eb2a995d735e64ec is a bit drastic.
=> [cmake] Disable finding Doxygen only for CMake < 3.28

SRC/colamd.c, SRC/dcomplex.c, SRC/dgstrs.c, SRC/get_perm_c.c, SRC/ilu_relax_snode.c, SRC/mark_relax.c, SRC/mmd.c, SRC/relax_snode.c, SRC/slu_dcomplex.h, SRC/slu_ddefs.h, SRC/slu_util.h, SRC/sp_coletree.c, SRC/sp_preorder.c, SRC/sutil.c, SRC/util.c
Found by Cppcheck (constParameterPointer).
More details why this is a good idea: https://wiki.sei.cmu.edu/confluence/display/c/DCL13-C.+Declare+function+parameters+that+are+pointers+to+values+not+changed+by+the+function+as+const
=> Wherever possible declared parameter as pointer to const
